/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KOXSoftwarePB;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Ramka służąca edycji studentów
 */
public class CF_ClientEdit extends javax.swing.JFrame {

    /**
     * Konstruktor tworzący nową ramke
     * @param cnx Obiekt do polaczenia z baza danych
     * @param stmt Sluzy do wykonania kwerendy
     */
    public CF_ClientEdit() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        StudentEdit_UpdateStudent_Button.setVisible(false);
        
        
    
    }
    /**
     * Funckja która wyświetla studenta po id
     * @param cnx Obiekt połącznia z bazą
     * @param model Tabela do wyświetlania danych
     * @param i Licznik, zmienna służaca dodawaniu kolejnych wierszy
     * @param fromInt Zmienna przechowująca id Studenta
     * @param sqlQuery Zmienna przechowująca kwerendę
     * @param what Zmienna przechowująca typ pola po którym wyszukujemy wartość
     * @param stmt Sluzy do wykonania kwerendy
     * @param rs Słuzy do przechowywania rezultatów kwerendy
     * @param ShowStudent Obiekt klasy CStudenciP
     * @throws e Sprawdzenie czy połączenie z bazą przebiegło pomyslnie
     */
    public void PokazywanieStudenta(DefaultTableModel model) throws Exception{
        String what = "";
        int fromInt=1;
        String sqlQuery="";
        int cardNumberTemp=0;
        String nameTemp="";
        String surnameTemp="";
        String peselTemp="";
        String loginTemp="";
        String passwordTemp="";
        Connection myConn = MySQLConnection.getConnection();
        try {
                fromInt = Integer.parseInt(ClientEdit_ClientId_Text.getText());
            }
        catch(NumberFormatException e) {
			showMessageDialog(null,"To nie jest liczba!");
                        fromInt=0;
                        ClientEdit_ClientId_Text.setText("");
		}
        
        try {
                Statement stmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                what="klienci.KLI_CARD_NUMBER";
                sqlQuery="SELECT KLI_CARD_NUMBER,KLI_NAME,KLI_SURNAME,KLI_PESEL,LOG_LOGIN,LOG_PASSWORD FROM login INNER JOIN klienci ON login.lOG_UID=klienci.KLI_LOGIN_ID WHERE "+what+" LIKE '"+fromInt+"' ;";
                ResultSet rs = stmt.executeQuery(sqlQuery);
                if (rs.next()==false){
                    showMessageDialog(null,"Brak klienta o danym id");
                    return;
                }
                rs.beforeFirst();
                while (rs.next()) {
                    model.addRow(new Object[6]);
                    cardNumberTemp=rs.getInt("KLI_CARD_NUMBER");
                    nameTemp=rs.getString("KLI_NAME");
                    surnameTemp=rs.getString("KLI_SURNAME");
                    peselTemp=rs.getString("KLI_PESEL");
                    loginTemp=rs.getString("LOG_LOGIN");
                    passwordTemp=rs.getString("LOG_PASSWORD");
                    ClientEdit_ClientData_Table.setValueAt(cardNumberTemp, 0, 0);
                    ClientEdit_ClientData_Table.setValueAt(nameTemp, 0, 1);
                    ClientEdit_ClientData_Table.setValueAt(surnameTemp, 0, 2);
                    ClientEdit_ClientData_Table.setValueAt(peselTemp, 0, 3);
                    ClientEdit_ClientData_Table.setValueAt(loginTemp, 0, 4);
                    ClientEdit_ClientData_Table.setValueAt(passwordTemp, 0, 5);
                    ClientEdit_Name_Text.setText(nameTemp);
                    ClientEdit_SurName_Text.setText(surnameTemp);
                    ClientEdit_Pesel_Text.setText(peselTemp);
                    ClientEdit_Login_Text.setText(loginTemp);
                    ClientEdit_Password_Text.setText(passwordTemp);
                    ClientEdit_Password2_Text.setText(passwordTemp);
                    StudentEdit_UpdateStudent_Button.setVisible(true);
                }
            }
        catch (SQLException e) {
               showMessageDialog(null, "Problem z połaczeniem");
    }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientEdit_Header = new javax.swing.JLabel();
        ClientEdit_Label2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientEdit_ClientId_Text = new javax.swing.JTextPane();
        ClientEdit_Header_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientEdit_ClientData_Table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClientEdit_Name_Text = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ClientEdit_SurName_Text = new javax.swing.JTextPane();
        StudentEdit_UpdateStudent_Button = new javax.swing.JButton();
        StudentEdit_NoChanges_Button = new javax.swing.JButton();
        StudentEdit_Close_Button = new javax.swing.JButton();
        ClientPoints_ShowData_Button = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ClientEdit_Pesel_Text = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        ClientEdit_Login_Text = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ClientEdit_Password_Text = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        ClientEdit_Password2_Text = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClientEdit_Header.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        ClientEdit_Header.setForeground(new java.awt.Color(255, 153, 153));
        ClientEdit_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientEdit_Header.setText("STACJA PALIW");
        ClientEdit_Header.setToolTipText("");

        ClientEdit_Label2.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        ClientEdit_Label2.setForeground(new java.awt.Color(0, 204, 204));
        ClientEdit_Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientEdit_Label2.setText("Podaj Numer Karty Klienta");

        jScrollPane1.setViewportView(ClientEdit_ClientId_Text);

        ClientEdit_Header_Label.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        ClientEdit_Header_Label.setForeground(new java.awt.Color(0, 204, 204));
        ClientEdit_Header_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientEdit_Header_Label.setText("Obecne dane klienta");

        ClientEdit_ClientData_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Imie", "Nazwisko", "Pesel", "Login", "Hasło"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ClientEdit_ClientData_Table);

        jLabel4.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Edytuj nazwisko:");
        jLabel4.setMaximumSize(new java.awt.Dimension(198, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(198, 25));

        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Edytuj pesel:");

        jLabel7.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Edytuj imie:");
        jLabel7.setMaximumSize(new java.awt.Dimension(198, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(198, 25));

        jScrollPane3.setViewportView(ClientEdit_Name_Text);

        jScrollPane5.setViewportView(ClientEdit_SurName_Text);

        StudentEdit_UpdateStudent_Button.setBackground(new java.awt.Color(255, 255, 102));
        StudentEdit_UpdateStudent_Button.setText("Zaktualizuj dane");
        StudentEdit_UpdateStudent_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentEdit_UpdateStudent_ButtonActionPerformed(evt);
            }
        });

        StudentEdit_NoChanges_Button.setBackground(new java.awt.Color(255, 0, 0));
        StudentEdit_NoChanges_Button.setText("Wróc do menu głownego");
        StudentEdit_NoChanges_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentEdit_NoChanges_ButtonActionPerformed(evt);
            }
        });

        StudentEdit_Close_Button.setBackground(new java.awt.Color(255, 0, 0));
        StudentEdit_Close_Button.setText("Wyłącz program");
        StudentEdit_Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentEdit_Close_ButtonActionPerformed(evt);
            }
        });

        ClientPoints_ShowData_Button.setBackground(new java.awt.Color(255, 255, 102));
        ClientPoints_ShowData_Button.setText("Pokaż dane");
        ClientPoints_ShowData_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientPoints_ShowData_ButtonActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(ClientEdit_Pesel_Text);

        jLabel8.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Edytuj login:");

        jScrollPane7.setViewportView(ClientEdit_Login_Text);

        jLabel9.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Edytuj hasło:");

        jScrollPane8.setViewportView(ClientEdit_Password_Text);

        jLabel10.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Potwierdź hasło:");

        jScrollPane9.setViewportView(ClientEdit_Password2_Text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane9)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClientEdit_Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                            .addComponent(ClientEdit_Header_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StudentEdit_Close_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(StudentEdit_NoChanges_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                    .addComponent(StudentEdit_UpdateStudent_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClientEdit_Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClientPoints_ShowData_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ClientEdit_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(ClientEdit_Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ClientPoints_ShowData_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ClientEdit_Header_Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(StudentEdit_UpdateStudent_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(StudentEdit_NoChanges_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentEdit_Close_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Funckja która aktualizuje dane studenta 
     * @param cnx Obiekt połącznia z bazą
     * @param model Tabela do wyświetlania danych
     * @param fromInt Zmienna przechowująca id Studenta
     * @param grpInt Zmienna przechowująca grupe Studenta
     * @param Imie Zmienna przechowująca imie Studenta
     * @param Nazwisko Zmienna przechowująca nazwisko Studenta
     * @param Stypendium Zmienna przechowująca stypendium Studenta
     * @param sqlQuery1 Zmienna przechowująca kwerendę1
     * @param sqlQuery2 Zmienna przechowująca kwerendę2
     * @param sqlQuery3 Zmienna przechowująca kwerendę3
     * @param stmt Sluzy do wykonania kwerendy
     * @param rs Słuzy do przechowywania rezultatów kwerendy
     * @throws e Sprawdzenie czy połączenie z bazą przebiegło pomyslnie
     */
    private void StudentEdit_UpdateStudent_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentEdit_UpdateStudent_ButtonActionPerformed
        int fromInt= Integer.parseInt(ClientEdit_ClientId_Text.getText());
        String name=ClientEdit_Name_Text.getText();
        String surname=ClientEdit_SurName_Text.getText();
        String pesel=ClientEdit_Pesel_Text.getText();
        String login=ClientEdit_Login_Text.getText();
        String password=ClientEdit_Password_Text.getText();
        String password2=ClientEdit_Password2_Text.getText();
        int loginUID=0;
        showMessageDialog(null,password);
        showMessageDialog(null,password2);
        if(password.equals(password2)==false){
            showMessageDialog(null,"Ustaw takie same hasła!!!");                        
            return;
        }
        Connection myConn;
        try {
            myConn = MySQLConnection.getConnection();
            Statement stmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sqlQuery="SELECT LOG_UID FROM login INNER JOIN klienci ON login.lOG_UID=klienci.KLI_LOGIN_ID WHERE klienci.KLI_CARD_NUMBER LIKE '"+fromInt+"' ;";
            ResultSet rs = stmt.executeQuery(sqlQuery);
            while (rs.next()) {
                loginUID=rs.getInt("LOG_UID");
            }
            sqlQuery="UPDATE klienci SET KLI_NAME ='"+name+"',KLI_SURNAME='"+surname+"',KLI_PESEL='"+pesel+"' WHERE KLI_CARD_NUMBER="+fromInt+";";
            String sqlQuery2="UPDATE login SET LOG_LOGIN='"+login+"',LOG_PASSWORD='"+password+"' WHERE LOG_UID="+loginUID+";";
            stmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            String sqlQuery3="SELECT * FROM klienci WHERE KLI_CARD_NUMBER="+fromInt+"";
            rs = stmt.executeQuery(sqlQuery3);
            if (rs.first()==false){
                showMessageDialog(null,"Brak KLIENTA o danym id");
                return;
            }
            stmt = myConn.createStatement();
            stmt.executeUpdate(sqlQuery);
            stmt.executeUpdate(sqlQuery2);
            showMessageDialog(null,"Pomyślnie zaktualizowano");
            String n[]={"Numer karty","Imie","Nazwisko","Pesel","Login","Hasło"};
            DefaultTableModel model=new DefaultTableModel(null,n);
            ClientEdit_ClientData_Table.setModel(model);
            PokazywanieStudenta(model);
            ClientEdit_Name_Text.setText("");
            ClientEdit_SurName_Text.setText("");
            ClientEdit_Pesel_Text.setText("");
            ClientEdit_Login_Text.setText("");
            ClientEdit_Password_Text.setText("");
            ClientEdit_Password2_Text.setText("");
            StudentEdit_UpdateStudent_Button.setVisible(false);
            ClientEdit_ClientId_Text.setText("");
            
        } catch (Exception ex) {
            Logger.getLogger(CF_ClientEdit.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null, "Nie można połączyć z bazą");
        }
        
        
               
    
        
        
    }//GEN-LAST:event_StudentEdit_UpdateStudent_ButtonActionPerformed
    /**
     * Metoda sluząca wyjściu z ramki
     */
    private void StudentEdit_NoChanges_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentEdit_NoChanges_ButtonActionPerformed
        new  CF_MainMenuAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StudentEdit_NoChanges_ButtonActionPerformed
    /**
     * Metoda sluząca zakończeniu działania aplikacji
     */
    private void StudentEdit_Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentEdit_Close_ButtonActionPerformed
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_StudentEdit_Close_ButtonActionPerformed
    /**
     * Metoda pośrednicząca w wyswietlaniu danych studenta po id
     * @param n Wzór tablei
     * @param cnx Obiekt do polaczenia z baza danych
     */
    private void ClientPoints_ShowData_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientPoints_ShowData_ButtonActionPerformed
        String n[]={"Numer karty","Imie","Nazwisko","Pesel","Login","Hasło"};
        DefaultTableModel model=new DefaultTableModel(null,n);
        ClientEdit_ClientData_Table.setModel(model);
        try {
            PokazywanieStudenta(model);
        } catch (Exception ex) {
            Logger.getLogger(CF_ClientEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ClientPoints_ShowData_ButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CF_ClientEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CF_ClientEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CF_ClientEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CF_ClientEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CF_ClientEdit().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientEdit_ClientData_Table;
    private javax.swing.JTextPane ClientEdit_ClientId_Text;
    private javax.swing.JLabel ClientEdit_Header;
    private javax.swing.JLabel ClientEdit_Header_Label;
    private javax.swing.JLabel ClientEdit_Label2;
    private javax.swing.JTextPane ClientEdit_Login_Text;
    private javax.swing.JTextPane ClientEdit_Name_Text;
    private javax.swing.JTextPane ClientEdit_Password2_Text;
    private javax.swing.JTextPane ClientEdit_Password_Text;
    private javax.swing.JTextPane ClientEdit_Pesel_Text;
    private javax.swing.JTextPane ClientEdit_SurName_Text;
    private javax.swing.JButton ClientPoints_ShowData_Button;
    private javax.swing.JButton StudentEdit_Close_Button;
    private javax.swing.JButton StudentEdit_NoChanges_Button;
    private javax.swing.JButton StudentEdit_UpdateStudent_Button;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    // End of variables declaration//GEN-END:variables
}
