/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package KOXSoftwarePB;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import static javax.swing.JOptionPane.showMessageDialog;



 /**
 * Program służacy do obsługi bazy danych dla placówki dydaktycznej
 * @author Kusek Jan Aleksander Krawiec
 * @version 1.0
 * @see CFrameStudents
 * @see CFrameAvailableClass
 * @see CFrameClassAddDelete
 * @see CFrameClassEdit
 * @see CFrameFindStudent
 * @see CFrameTeacher
 * @see CFrameStudentsAddDelete
 * @see CFrameStudentsMoney
 * @see CFrameSubjectAddDelete
 * @see CFrameTeacher
 * @see CFrameTeacherAssignment
 * @see CFrameTeachersAddDelete
 * @see java.sql
 * @see java.swing
*/
 
public class CF_MainMenuUser extends javax.swing.JFrame {

    /**
     * Tworzy nową ramke menu głownego
     */
    public CF_MainMenuUser() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }
    
    /**
     * Odpowiada za każde połączenie z bazą danych
     * @param cnx Obiekt połącznia z bazą
     * @param driver Driver służący do połączenia
     * @param url Adres połączenia
     * @param user Nazwa użytkownika w bazie
     * @param password Hasło użytkownika w bazie
     * @throws e Sprawdzenie czy połączenie z bazą przebiegło pomyslnie
     */
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Main_CloseProgram_Button = new javax.swing.JButton();
        MMA_CarWashReservations = new javax.swing.JButton();
        MMA_PointsUser = new javax.swing.JButton();
        MMA_PriceList = new javax.swing.JButton();
        MMA_TransactionUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stacja paliw");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Panel Klienta");

        Main_CloseProgram_Button.setBackground(new java.awt.Color(255, 0, 0));
        Main_CloseProgram_Button.setText("Wyłącz program");
        Main_CloseProgram_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_CloseProgram_ButtonActionPerformed(evt);
            }
        });

        MMA_CarWashReservations.setBackground(new java.awt.Color(0, 255, 255));
        MMA_CarWashReservations.setText("Zarezerwuj Mycie");
        MMA_CarWashReservations.setMaximumSize(new java.awt.Dimension(149, 23));
        MMA_CarWashReservations.setMinimumSize(new java.awt.Dimension(149, 23));
        MMA_CarWashReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMA_CarWashReservationsActionPerformed(evt);
            }
        });

        MMA_PointsUser.setBackground(new java.awt.Color(0, 255, 255));
        MMA_PointsUser.setText("Liczba punktów");
        MMA_PointsUser.setMaximumSize(new java.awt.Dimension(149, 23));
        MMA_PointsUser.setMinimumSize(new java.awt.Dimension(149, 23));
        MMA_PointsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMA_PointsUserActionPerformed(evt);
            }
        });

        MMA_PriceList.setBackground(new java.awt.Color(0, 255, 255));
        MMA_PriceList.setText("Sprawdź cennik");
        MMA_PriceList.setMaximumSize(new java.awt.Dimension(149, 23));
        MMA_PriceList.setMinimumSize(new java.awt.Dimension(149, 23));
        MMA_PriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMA_PriceListActionPerformed(evt);
            }
        });

        MMA_TransactionUser.setBackground(new java.awt.Color(0, 255, 255));
        MMA_TransactionUser.setText("Historia transakcji");
        MMA_TransactionUser.setMaximumSize(new java.awt.Dimension(149, 23));
        MMA_TransactionUser.setMinimumSize(new java.awt.Dimension(149, 23));
        MMA_TransactionUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMA_TransactionUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Main_CloseProgram_Button)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MMA_CarWashReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MMA_PriceList, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MMA_TransactionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MMA_PointsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(MMA_CarWashReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MMA_PriceList, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MMA_TransactionUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MMA_PointsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Main_CloseProgram_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MMA_CarWashReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMA_CarWashReservationsActionPerformed
        
        try {
            CF_ReservationsUser CF_ReservationsUserObject=new CF_ReservationsUser();
            CF_ReservationsUserObject.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(CF_MainMenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MMA_CarWashReservationsActionPerformed
    /**
     * Metoda sluząca zakończeniu działania aplikacji
     */
    private void Main_CloseProgram_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_CloseProgram_ButtonActionPerformed
        Runtime.getRuntime().exit(0); 
    }//GEN-LAST:event_Main_CloseProgram_ButtonActionPerformed

    private void MMA_PointsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMA_PointsUserActionPerformed
        
        CF_ClientPointsUser CF_ClientPointsUserObject=new CF_ClientPointsUser();
        CF_ClientPointsUserObject.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_MMA_PointsUserActionPerformed

    private void MMA_PriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMA_PriceListActionPerformed
        // TODO add your handling code here:
        CF_PriceListUser CF_PriceListUserObject=new CF_PriceListUser();
        CF_PriceListUserObject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MMA_PriceListActionPerformed

    private void MMA_TransactionUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMA_TransactionUserActionPerformed
        try {
            CF_TransactionsListUser CF_TransactionsListUserObject = new CF_TransactionsListUser();
            CF_TransactionsListUserObject.setVisible(true);
            this.dispose();
            // TODO add your handling code here:
        } catch (ParseException ex) {
            Logger.getLogger(CF_MainMenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MMA_TransactionUserActionPerformed
    
   /*  static void nawiazywaniePolaczenia() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://34.89.209.127:3306/BazaDanychLaboratorium?useUnicode=true&characterEncoding=utf-8", "qwertyprzem", "18198996");
            showMessageDialog(null, "Dziaa");
        } catch (Exception e) {
            String komunikat = "Nie udało się połączyć z bazą danych. Komunikat błędu:\n" + e;
            showMessageDialog(null, komunikat);
            Runtime.getRuntime().exit(0);
        }
    }
    */
    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CF_MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CF_MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CF_MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CF_MainMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            /**
             * @param CFrameMainMenuObject Obiekt klasy CFrameMainMenu
             */        
            public void run() {
                CF_MainMenuUser CFrameMainMenuObject= new CF_MainMenuUser();
                CFrameMainMenuObject.setVisible(true);
                
            }
            
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MMA_CarWashReservations;
    private javax.swing.JButton MMA_PointsUser;
    private javax.swing.JButton MMA_PriceList;
    private javax.swing.JButton MMA_TransactionUser;
    private javax.swing.JButton Main_CloseProgram_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
