/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KOXSoftwarePB;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Ramka służąca edycji studentów
 */
public class CF_PriceListUser extends javax.swing.JFrame {

    /**
     * Konstruktor tworzący nową ramke
     * @param cnx Obiekt do polaczenia z baza danych
     * @param stmt Sluzy do wykonania kwerendy
     */
    public CF_PriceListUser() {
        
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            String n[]={"Usługa","Cena"};
            DefaultTableModel model=new DefaultTableModel(null,n);
            PriceListUser_PriceData_Table.setModel(model);     
        try { 
            PokazywanieDanychCennika(model);
            
            
        } catch (Exception ex) {
            Logger.getLogger(CF_PriceListUser.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
    
    
    }
     public void PokazywanieDanychCennika(DefaultTableModel model) throws Exception{
        String what = "";
        int counter=0;
        String sqlQuery="";
        double priceTemp=0;
        String nameTemp="";
        String newPrice="";
        String newPrice2="";
        Connection myConn = MySQLConnection.getConnection();
        
        
        try {
            Statement stmt = myConn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            what="cennik.CEN_DESCRIPTION";                
            sqlQuery="SELECT * FROM cennik;";
            ResultSet rs = stmt.executeQuery(sqlQuery);
            while (rs.next()) {
                    model.addRow(new Object[2]);
                    priceTemp=rs.getDouble("CEN_PRICE");
                    nameTemp=rs.getString("CEN_DESCRIPTION");
                    PriceListUser_PriceData_Table.setValueAt(nameTemp, counter, 0);
                    PriceListUser_PriceData_Table.setValueAt(priceTemp, counter, 1);
                    
                    if(!(nameTemp.equals("Mycie")||nameTemp.equals("Mycie z woskowaniem"))){
                        newPrice=String.valueOf(priceTemp)+" zł/l";
                        PriceListUser_PriceData_Table.setValueAt(nameTemp, counter, 0);
                        PriceListUser_PriceData_Table.setValueAt(newPrice, counter, 1);
                    }else
                    {
                        newPrice2=String.valueOf(priceTemp)+" zł";
                        PriceListUser_PriceData_Table.setValueAt(nameTemp, counter, 0);
                        PriceListUser_PriceData_Table.setValueAt(newPrice2, counter, 1);
                        
                    }
                    
                    counter++;
            }
            }
        catch (SQLException e) {
               showMessageDialog(null, "Problem z połaczeniem");
    }
            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientEdit_Header = new javax.swing.JLabel();
        PriceList_Header_Label = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PriceListUser_PriceData_Table = new javax.swing.JTable();
        PriceList_NoChanges_Button = new javax.swing.JButton();
        PriceList_Close_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClientEdit_Header.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        ClientEdit_Header.setForeground(new java.awt.Color(255, 153, 153));
        ClientEdit_Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientEdit_Header.setText("STACJA PALIW");
        ClientEdit_Header.setToolTipText("");

        PriceList_Header_Label.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        PriceList_Header_Label.setForeground(new java.awt.Color(0, 204, 204));
        PriceList_Header_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PriceList_Header_Label.setText("Aktualny cennik");

        PriceListUser_PriceData_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Usługa", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PriceListUser_PriceData_Table);

        PriceList_NoChanges_Button.setBackground(new java.awt.Color(255, 0, 0));
        PriceList_NoChanges_Button.setText("Wróc do menu głownego");
        PriceList_NoChanges_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceList_NoChanges_ButtonActionPerformed(evt);
            }
        });

        PriceList_Close_Button.setBackground(new java.awt.Color(255, 0, 0));
        PriceList_Close_Button.setText("Wyłącz program");
        PriceList_Close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceList_Close_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PriceList_NoChanges_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(PriceList_Close_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClientEdit_Header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceList_Header_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClientEdit_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PriceList_Header_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(PriceList_NoChanges_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PriceList_Close_Button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   /**
     * Metoda sluząca wyjściu z ramki
     */
    private void PriceList_NoChanges_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceList_NoChanges_ButtonActionPerformed
        new  CF_MainMenuUser().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PriceList_NoChanges_ButtonActionPerformed
    /**
     * Metoda sluząca zakończeniu działania aplikacji
     */
    private void PriceList_Close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceList_Close_ButtonActionPerformed
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_PriceList_Close_ButtonActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CF_PriceListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CF_PriceListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CF_PriceListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CF_PriceListUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CF_PriceListUser().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClientEdit_Header;
    private javax.swing.JTable PriceListUser_PriceData_Table;
    private javax.swing.JButton PriceList_Close_Button;
    private javax.swing.JLabel PriceList_Header_Label;
    private javax.swing.JButton PriceList_NoChanges_Button;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
